### ISSUE TITLE
i got error

### ISSUE THREAD

**Issue by bsdis** [strothj/cra-bug-export-star-not-supported#1]
Hi,

I tried cloning, running npm install and then npm start which resulted in this error

<img width="575" alt="Screenshot 2020-04-01 at 18 31 57" src="https://user-images.githubusercontent.com/1256202/78162480-36da5600-7447-11ea-83b5-d51616586c4b.png">

**Comment by strothj** [comment]
Yes, this is intentional. This repo is to demonstrate the problem referenced in the Github issue.
